before:
  hooks:
    - go generate .

builds:
  - binary: webexec
    id: non-darwin
    goos:
      - linux
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
  - binary: webexec
    id: darwin
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    hooks:
      post:
        - |
          sh -c '
          fn=dist/darwin_{{.Target}}/gon.hcl
          cat >"$fn" <<EOF
          bundle_id = "{{.Env.BUNDLE_ID}}"
          apple_id {
            username = "{{.Env.APPLE_ID_USERNAME}}"
            password = "{{.Env.APPLE_ID_PASSWORD}}"
          }
          source = ["dist/darwin_{{.Target}}/{{.Name}}"]
          sign {
            application_identity = "{{.Env.APPLE_APPLICATION_IDENTITY}}"
          }
          EOF
          '
        - "gon -log-level=debug 'dist/darwin_{{.Target}}/gon.hcl'"

archives:
  - id: non-darwin
    builds: [non-darwin]
      # name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - replace_n_launch.sh
  - id: darwin
    builds: [darwin]
    format: zip
      # name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - replace_n_launch.sh
    wrap_in_directory: true

signs:
  - id: darwin-notarized
    ids: [darwin]
    signature: "${artifact}"
      # output: true
    cmd: sh
    args:
      - "-c"
      - |-
        cat >"dist/gon.notarize.hcl" <<EOF
        apple_id {
          username = "{{.Env.APPLE_ID_USERNAME}}"
          password = "{{.Env.APPLE_ID_PASSWORD}}"
        }
        notarize {
          path = "${artifact}"
          bundle_id = "{{.Env.BUNDLE_ID}}"
        }
        EOF
        gon "dist/gon.notarize.hcl"
    artifacts: archive

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
release:
   ids: [non-darwin, darwin-notarized]
   github:
     owner: tuzig
     name: webexec
   draft: true
   prerelease: auto
   footer: ...[Here](https://github.com/tuzig/webexec/blob/master/CHANGELOG.md) for the complete change log
   replace_existing_draft: true
